version: 0.2

phases:
  install:
    commands:
      - composer install
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files: '**/*'
  name: jamfluencer-api-$(date +%Y-%m-%d)
  exclude-paths:
    - "**/.*"
